apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: azurewebsiets
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storageAccountName | b64enc | quote }}
  azurestorageaccountkey: {{ .Values.storageAccountKey | b64enc | quote }}